hun2eng = {
    "Rendszer-irány (kWh)": "System Direction (kWh)",
    "Pozitív Mérlegköri kiegyenlítő energia egységára (HUF/kWh)": "Positive Balancing Energy Unit Price for Balance Groups (HUF/kWh)",
    "Negatív Mérlegköri kiegyenlítő energia egységára (HUF/kWh)": "Negative Balancing Energy Unit Price for Balance Groups (HUF/kWh)",
    "Szélerőművek becsült termelése (aktuális)": "Estimated Wind Power Production (Current)",
    "Szélerőművek becsült termelése (dayahead)": "Estimated Wind Power Production (Day-Ahead)",
    "Szélerőművek becsült termelése (intraday)": "Estimated Wind Power Production (Intraday)",
    "Naperőművek becsült termelése (aktuális)": "Estimated Solar Power Production (Current)",
    "Naperőművek becsült termelése (intraday)": "Estimated Solar Power Production (Intraday)",
    "Naperőművek becsült termelése (dayahead)": "Estimated Solar Power Production (Day-Ahead)",
    "Bruttó terv erőművi termelés": "Gross Planned Power Plant Generation",
    "Bruttó rendszerterhelés becslés (dayahead)": "Gross System Load Forecast (Day-Ahead)",
    "HU-AT menetrend": "HU-AT Schedule",
    "HU-HR menetrend": "HU-HR Schedule",
    "HU-SK menetrend": "HU-SK Schedule",
    "HU-RS menetrend": "HU-RS Schedule",
    "HU-UK menetrend": "HU-UA Schedule",
    "HU-RO menetrend": "HU-RO Schedule",
    "HU-SI menetrend (RIR NT)": "HU-SI Schedule (RIR NT)",
    "Bruttó hitelesített rendszerterhelés tény": "Gross Certified System Load (Actual)",
    "Bruttó terv rendszerterhelés": "Gross Planned System Load",
    "Bruttó tény erőművi termelés": "Gross Actual Power Plant Generation",
    "Bruttó tény rendszerterhelés": "Gross Actual System Load",
    "HU-AT": "HU-AT",
    "HU-HR": "HU-HR",
    "HU-RO": "HU-RO",
    "HU-RS": "HU-RS",
    "HU-SK": "HU-SK",
    "HU-UK": "HU-UA",
    "HU-SI": "HU-SI",
    "Igényelt Negatív aFRR kiegyenlítő szabályozási energia (kWh)": "Requested Negative aFRR Balancing Energy (kWh)",
    "Igényelt Pozitív aFRR kiegyenlítő szabályozási energia (kWh)": "Requested Positive aFRR Balancing Energy (kWh)",
    "Naperőművek nettó üzemirányítási": "Solar Power Plants Net (Operational Control)",
    "Ipari naperőművek nettó kereskedelmi": "Solar Power Plants Net (Commercial)",
    "Negative Balancing Energy Unit Price for Balance Groups (HUF/kWh)": "Negative Balancing Energy Unit Price for Balance Groups (HUF/kWh)",
    "Negatív GCC energia (kWh)": "Negative GCC Energy (kWh)",
    "Negatív aFRR aktivált kiegyenlítő szabályozási energia (kWh)": "Activated Negative aFRR Balancing Energy (kWh)",
    "Negatív aFRR aktivált kiegyenlítő szabályozási energia díja (HUF)": "Activated Negative aFRR Balancing Energy Cost (HUF)",
    "Negatív mFRR és RR aktivált kiegyenlítő szabályozási energia (kWh)": "Activated Negative mFRR and RR Balancing Energy (kWh)",
    "Negatív mFRR és RR aktivált kiegyenlítő szabályozási energia díja (HUF)": "Activated Negative mFRR and RR Balancing Energy Cost (HUF)",
    "Nettó hazai termelés tény": "Net Domestic Generation (Actual)",
    "Nettó rendszerterhelés becslés (dayahead)": "Net System Load Forecast (Day-Ahead)",
    "Nettó rendszerterhelés tény - üzemirányítási": "Net System Load (Actual - Operational Control)",
    "Nettó terhelés": "Net Load",
    "Nettó terv erőművi termelés": "Net Planned Power Plant Generation",
    "Nettó terv rendszerterhelés": "Net Planned System Load",
    "Nettó terv rendszertermelés": "Net Planned System Generation",
    "Nettó tény rendszerterhelés - net.ker.elsz.meres": "Net Actual System Load - Net Commercial Settlement Measurement",
    "Positive Balancing Energy Unit Price for Balance Groups (HUF/kWh)": "Positive Balancing Energy Unit Price for Balance Groups (HUF/kWh)",
    "Pozitív GCC energia (kWh)": "Positive GCC Energy (kWh)",
    "Pozitív aFRR aktivált kiegyenlítő szabályozási energia (kWh)": "Activated Positive aFRR Balancing Energy (kWh)",
    "Pozitív aFRR aktivált kiegyenlítő szabályozási energia díja (HUF)": "Activated Positive aFRR Balancing Energy Cost (HUF)",
    "Pozitív mFRR és RR aktivált kiegyenlítő szabályozási energia (kWh)": "Activated Positive mFRR and RR Balancing Energy (kWh)",
    "Pozitív mFRR és RR aktivált kiegyenlítő szabályozási energia díja (HUF)": "Activated Positive mFRR and RR Balancing Energy Cost (HUF)",
    "System Direction (kWh)": "System Direction (kWh)",
    "Szélerőművek tény - nettó kereskedelmi elszámolási": "Wind Power Actual - Net Commercial Settlement",
    "Szélerőművek tény - nettó üzemirányítási": "Wind Power Actual - Net Operational Control",
    "Szélerőművek tény - bruttó üzemirányítási": "Wind Power Actual - Gross Operational Control",
    "Szélerőművek tény - bruttó üzemirányítási 1p": "Wind Power Actual - Gross Operational Control 1p",
}

eng2hun = {v: k for k, v in hun2eng.items()}

for v in hun2eng.values():
    print(f"    \\item {v}")
